local STRINGS = GLOBAL.STRINGS

-- The character select screen lines
STRINGS.CHARACTER_TITLES.winslow = "Winslow"
STRINGS.CHARACTER_NAMES.winslow = "Esc"
STRINGS.CHARACTER_DESCRIPTIONS.winslow = "*Good at music, bad at everything else.\n*War child\n*Used to eating rot"
STRINGS.CHARACTER_QUOTES.winslow = "\"Quote\""
STRINGS.CHARACTER_SURVIVABILITY.winslow = "Slim"

-- Custom speech strings
STRINGS.CHARACTERS.WINSLOW = require "speech_winslow"

-- The character's name as appears in-game
STRINGS.NAMES.WINSLOW = "Winslow"
STRINGS.SKIN_NAMES.winslow_none = "Winslow"

STRINGS.NAMES.BATON = "Conductor's baton"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BATON = "Conductor's baton"

STRINGS.NAMES.VIOLIN = "Violin"
STRINGS.NAMES.DRUM = "Drum"
STRINGS.NAMES.CLARINET = "Clarinet"
STRINGS.NAMES.BASS = "Bass"
STRINGS.NAMES.TROMBONE = "Trombone"
STRINGS.NAMES.GUITAR = "Guitar"
STRINGS.NAMES.PIANO = "Piano"
STRINGS.NAMES.SAXOPHONE = "Saxophone"
STRINGS.NAMES.SHAMISEN = "Shamisen"

STRINGS.RECIPE_DESC.VIOLIN = "Violin"
STRINGS.RECIPE_DESC.DRUM = "Drum"
STRINGS.RECIPE_DESC.CLARINET = "Clarinet"
STRINGS.RECIPE_DESC.BASS = "Bass"
STRINGS.RECIPE_DESC.TROMBONE = "Trombone"
STRINGS.RECIPE_DESC.GUITAR = "Guitar"
STRINGS.RECIPE_DESC.PIANO = "Piano"
STRINGS.RECIPE_DESC.SAXOPHONE = "Saxophone"
STRINGS.RECIPE_DESC.SHAMISEN = "Shamisen"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.VIOLIN = "Violin"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRUM = "Drum"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLARINET = "Clarinet"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BASS = "Bass"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TROMBONE = "Trombone"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GUITAR = "Guitar"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIANO = "Piano"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAXOPHONE = "Saxophone"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHAMISEN = "Shamisen"

STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.BUILD.FULLORCHESTRA = "My orchestra is complete."
STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.BUILD.NOTREDY = "I'm not ready for a performance."

STRINGS.SKILLTREE.WINSLOW = {
  WINSLOW_BATTLE_PART_1_TITLE = "Test WINSLOW_BATTLE_PART_1",
  WINSLOW_BATTLE_PART_1_DESC = "Test WINSLOW_BATTLE_PART_1",

  WINSLOW_BATTLE_PART_2_TITLE = "Test WINSLOW_BATTLE_PART_2",
  WINSLOW_BATTLE_PART_2_DESC = "Test WINSLOW_BATTLE_PART_2",

  WINSLOW_CURSE_WEREMETER_3_TITLE = "Test WINSLOW_CURSE_WEREMETER_3",
  WINSLOW_CURSE_WEREMETER_3_DESC = "Test WINSLOW_CURSE_WEREMETER_3",

  WINSLOW_ALLEGIANCE_SHADOW_TITLE = "Test WINSLOW_ALLEGIANCE_SHADOW",
  WINSLOW_ALLEGIANCE_SHADOW_DESC = "Test WINSLOW_ALLEGIANCE_SHADOW",

  WINSLOW_ALLEGIANCE_REJECTED_TITLE = "Test WINSLOW_ALLEGIANCE_REJECTED",
  WINSLOW_ALLEGIANCE_REJECTED_DESC = "Test WINSLOW_ALLEGIANCE_REJECTED",

  WINSLOW_ALLEGIANCE_LUNAR_TITLE = "Test WINSLOW_ALLEGIANCE_LUNAR",
  WINSLOW_ALLEGIANCE_LUNAR_DESC = "Test WINSLOW_ALLEGIANCE_LUNAR",
}


STRINGS.SKILLTREE.ALLEGIANCE_LOCK_6_DESC = "Find and defeat the Ancient Fuelweaver and Celestial Champion."
STRINGS.SKILLTREE.ALLEGIANCE_LOCK_7_DESC = "Dont have any affinity"
