local TUNING = GLOBAL.TUNING

TUNING.WINSLOW_HEALTH = 90
TUNING.WINSLOW_HUNGER = 125
TUNING.WINSLOW_SANITY = 175
TUNING.ORCHESTRA_LIMIT = 6
TUNING.AFFINITY_15_CALORIES_VERYHUGE = 0.5
TUNING.INST_SHATTER_CHANCE = 0.5
TUNING.ALLY_INFLUENCE_RADIUS = 10

TUNING.DEFAULT_FORMATION_RADIUS = 3.5
